services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: proyinf
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"     # si 5432 ya est√° usado, cambia a "5433:5432"
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d proyinf"]
      interval: 5s
      timeout: 5s
      retries: 10
